import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Navbar from '../components/Navbar'


export default function About() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Home | Corea</title>
          <meta name="description" content="Generated by create next app About Page" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">About Page!</a>
          </h1>
  
          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/about.js</code>
          </p>
  
          <div className={styles.grid}>
            <Link href="/about" className={styles.card}>
              <h2>About &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </Link>
  
            <Link href="/" className={styles.card}>
                <h2>Home &rarr;</h2>
                <p>Learn about Next.js in an interactive course with quizzes!</p>
            </Link>
  
            <Link href="/contact" className={styles.card}>
                <h2>Contact &rarr;</h2>
                <p>Discover and deploy boilerplate example Next.js projects.</p>
            </Link>
  
            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>
      </div>
    )
  }