import Head from 'next/head'
import styles from './MainLayout.module.css'
import Link from 'next/link'
import Navbar from '../Navbar'


export default function MainLayout({children}) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Home | Corea</title>
          <meta name="description" content="Generated by create next app About Page" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        <main className={styles.main}>
            {children}
        </main>
      </div>
    )
  }
